apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-apps
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/sekthor/demo-manifests.git'
      targetRevision: main
      path: argocd/apps
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
