mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    # Logs → Loki (send to the gateway service, port 80)
    loki:
      endpoint: http://grafana-lgtm-loki-gateway/loki/api/v1/push

    # Metrics → Mimir (use nginx frontend, port 80)
    prometheusremotewrite:
      endpoint: http://grafana-lgtm-mimir-nginx/api/v1/push

    # Traces → Tempo (OTLP gRPC, distributor service on port 4317)
    otlp/tempo:
      endpoint: grafana-lgtm-tempo-distributor:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [loki]

      metrics:
        receivers: [otlp]
        exporters: [prometheusremotewrite]

      traces:
        receivers: [otlp]
        exporters: [otlp/tempo]
