mode: deployment

image:
  repository: otel/opentelemetry-collector-contrib

config:
  receivers:
    otlp:
      protocols:
        grpc:
        http:

  exporters:
    # Logs → Loki via OTLP → Loki Gateway
    otlphttp/loki:
      endpoint: http://grafana-lgtm-loki-gateway/otlp
      tls:
        insecure: true

    # Metrics → Mimir (via nginx frontend)
    prometheusremotewrite:
      endpoint: http://grafana-lgtm-mimir-nginx/api/v1/push

    # Traces → Tempo (via distributor, OTLP gRPC on 4317)
    otlp/tempo:
      endpoint: grafana-lgtm-tempo-distributor:4317
      tls:
        insecure: true

  service:
    pipelines:
      logs:
        receivers: [otlp]
        exporters: [otlphttp/loki]

      metrics:
        receivers: [otlp]
        exporters: [prometheusremotewrite]

      traces:
        receivers: [otlp]
        exporters: [otlp/tempo]