apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: argo-rollouts-demo 
spec:
  replicas: 5
  revisionHistoryLimit: 1

  selector:
    matchLabels:
      app: argo-rollouts-demo

  template:
    metadata:
      labels:
        app: argo-rollouts-demo 

    spec:
      containers:
        - name: nginx
          image: nginx:1.29.0
          ports:
          - name: http
            containerPort: 80
            protocol: TCP

  strategy:
    canary:
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
