apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: demo-app
spec:
  replicas: 5

  selector:
    matchLabels:
      app: demo-app 

  template:
    metadata:
      labels:
        app: demo-app 

    spec:
      containers:
        - name: nginx
          image: nginx:1.29.1
          ports:
          - name: http
            containerPort: 80
            protocol: TCP
          volumeMounts:
            - name: demo-app-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: demo-app-config
          configMap:
            name: demo-app-config

  strategy:
    canary:
      stableService: demo-app
      canaryService: demo-app-canary
      steps:
      - setWeight: 20
      - pause: {}
      - setWeight: 40
      - pause: {duration: 10}
      - setWeight: 60
      - pause: {duration: 10}
      - setWeight: 80
      - pause: {duration: 10}
