apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-app-config
data:
  default.conf: |
    server {
        listen 80;

        location / {
            access_log /dev/stdout;
            error_log /dev/stderr;
            return 200 'Hello, NGINX!\n';
        }
    }
