apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  project: default
  sources:
    - chart: argo-rollouts
      repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 2.40.4
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/argo-rollouts/values.yaml
    - repoURL: 'https://github.com/sekthor/demo-manifests.git'
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated: 
      enable: true
      prune: true
      selfHeal: true

  # make sure CRDs are not shown as out of sync 
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /spec/preserveUnknownFields
