apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/sekthor/demo-manifests.git'
      targetRevision: main
      path: demo-app
      
  destination:
    server: "https://kubernetes.default.svc"
    namespace: demo-app
