apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-lgtm
  namespace: argocd
spec:
  project: default
  sources:
    - chart: lgtm-distributed
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 2.1.0
      helm:
        valuesObject:
          tempo:
            ingester:
              ring:
                replication_factor: 1
  destination:
    server: "https://kubernetes.default.svc"
    namespace: grafana
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
